### ISSUE TITLE
Error on instances limit

### ISSUE THREAD

**Issue by guruvenkat7** [ralph-group/mucloud#14]
Hi,

Let me start off by thanking your release of MuCloud as it quite helpful.

I followed instructions on http://ralph-group.github.io/mucloud/install.html#stand-alone-executable to install Mucloud from source and for opening an AWS account. Things went without a hitch.

When I'm trying to run the standard problem 4, I get the error 

There are no instances waiting to be used.
Create a new instance for this simulation? [Yn]: Y
Traceback (most recent call last):
  File "mucloud.py", line 671, in <module>
    args.func(args)
  File "mucloud.py", line 494, in run_instance
    instance = group.ready_instance()
  File "mucloud.py", line 472, in ready_instance
    instance = Instance.launch()
  File "mucloud.py", line 434, in launch
    security_groups=config.get('EC2', 'SecurityGroups').split(',')
  File "C:\Users\phgv\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\boto\ec2\connection.py", line 973, in run_instances
    verb='POST')
  File "C:\Users\phgv\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\boto\connection.py", line 1207, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InstanceLimitExceeded</Code><Message>You have requested more instances (1) than your current instance limit of 0 allows for the specified instance type. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.</Message></Error></Errors><RequestID>6d97d2e4-f49e-40f4-b794-9dcd3fecff2f</RequestID></Response>

I went to the Limit page of my EC2 instances but have no idea which instance Mucloud is trying to launch. Is there anyway to find out? I can then ask for a limit on that instance.

Let me know if more information is required.

Regards,
Guru

**Comment by cjermain** [comment]
@guruvenkat7, I'm glad to hear that the instructions worked well. MuCloud uses a g2.2xlarge instance, which you can modify in your [config.ini file](https://github.com/ralph-group/mucloud/blob/master/config.ini#L36). AWS is usually very responsive on raising the limit for instances, so I expect you won't have a problem.

Please close this issue once you have it resolved, and feel free to ask further questions if not.

**Comment by cjermain** [comment]
@guruvenkat7, that is a good suggestion. The following code would need to be changed to have different messages based on the exception. Any interest in putting together a PR?
https://github.com/ralph-group/mucloud/blob/162e3a591518949ebf9a692e1497cdd837b12a48/mucloud.py#L189-L193

**Comment by guruvenkat7** [comment]
@cjermain I would be happy to be part of a PR for this purpose. However, I have not worked much on Github and will need to take a few lessons to do this. It maybe better if you create the PR.

For the case I faced, it'll just be enough to check if the '.pem' extension can be added. However, we could make the checks more comprehensive than that.

**Comment by guruvenkat7** [comment]
@cjermain Terribly sorry for the huge delay in replying to this. Some commitments had come up due to which I was unable to reply.

I tried changing the log.error to a log.exception (on line 192) and that does help. Now when the connection to the AWS instance does not happen, more sensible images are displayed.

If you create the PR, I can upload the improvement in the error messages there (along with any more ideas that come to me from paramiko's page).
